databases:
  - name: my-db  # Это просто название базы, можешь написать любое

services:
  - type: web
    name: my-django-app  # Тоже любое название, но без пробелов
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py migrate"
    startCommand: "gunicorn your_project_name.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
