# Generated by Django 5.1.7 on 2025-04-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='comments',
            field=models.ManyToManyField(blank=True, to='comments.comment'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='trainer',
            name='stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
